"""add_scheduled_publish_and_fields

Revision ID: 1a42ef3fd1d3
Revises: 9e633d01bdba
Create Date: 2026-08-15 18:03:23.687605

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a42ef3fd1d3'
down_revision: Union[str, None] = '9e633d01bdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_youtube_scheduled_publish', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('dry_run', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('dry_run')
        batch_op.drop_column('use_youtube_scheduled_publish')

    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
