"""Initial schema

Revision ID: 9e633d01bdba
Revises: 
Create Date: 2026-08-15 16:38:09.606072

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e633d01bdba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_title_template', sa.String(length=500), nullable=True),
    sa.Column('default_description_template', sa.Text(), nullable=True),
    sa.Column('default_tags', sa.JSON(), nullable=True),
    sa.Column('default_category_id', sa.String(length=10), nullable=True),
    sa.Column('default_privacy_status', sa.String(length=20), nullable=False),
    sa.Column('default_thumbnail_storage_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_youtube_channel_id'), ['youtube_channel_id'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.BigInteger(), 'postgresql').with_variant(sa.BigInteger(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_occurrence_id'), ['occurrence_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('content_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('storage_folder_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('default_title_template', sa.String(length=500), nullable=True),
    sa.Column('default_description_template', sa.Text(), nullable=True),
    sa.Column('default_tags', sa.JSON(), nullable=True),
    sa.Column('default_category_id', sa.String(length=10), nullable=True),
    sa.Column('default_thumbnail_storage_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_folders_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_folders_storage_folder_id'), ['storage_folder_id'], unique=True)

    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_credentials_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_credentials_service_type'), ['service_type'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('publish_time', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('upload_lead_minutes', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('days_of_month', sa.JSON(), nullable=True),
    sa.Column('one_time_date', sa.Date(), nullable=True),
    sa.Column('title_template', sa.String(length=500), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=10), nullable=True),
    sa.Column('privacy_status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_channel_id'), ['channel_id'], unique=False)

    op.create_table('shuffle_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('remaining_video_ids', sa.JSON(), nullable=False),
    sa.Column('used_video_ids', sa.JSON(), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_file_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('day_of_month_index', sa.Integer(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('custom_thumbnail_file_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['content_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_day_of_month_index'), ['day_of_month_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_storage_file_id'), ['storage_file_id'], unique=True)

    op.create_table('rotation_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('last_video_id', sa.String(length=36), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('schedule_occurrences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('scheduled_publish_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_upload_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_occurrences_youtube_video_id'), ['youtube_video_id'], unique=False)

    op.create_table('upload_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('temp_file_path', sa.String(length=1024), nullable=True),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('bytes_uploaded', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('youtube_resumable_uri', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['schedule_occurrences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_jobs_occurrence_id'), ['occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_upload_jobs_occurrence_id'))

    op.drop_table('upload_jobs')
    with op.batch_alter_table('schedule_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_video_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_schedule_occurrences_channel_id'))

    op.drop_table('schedule_occurrences')
    op.drop_table('rotation_states')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_storage_file_id'))
        batch_op.drop_index(batch_op.f('ix_videos_folder_id'))
        batch_op.drop_index(batch_op.f('ix_videos_day_of_month_index'))
        batch_op.drop_index(batch_op.f('ix_videos_channel_id'))

    op.drop_table('videos')
    op.drop_table('shuffle_states')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_channel_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_credentials_service_type'))
        batch_op.drop_index(batch_op.f('ix_oauth_credentials_channel_id'))

    op.drop_table('oauth_credentials')
    with op.batch_alter_table('content_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_folders_storage_folder_id'))
        batch_op.drop_index(batch_op.f('ix_content_folders_channel_id'))

    op.drop_table('content_folders')
    op.drop_table('system_settings')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_occurrence_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_module'))
        batch_op.drop_index(batch_op.f('ix_system_logs_level'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_logs_channel_id'))

    op.drop_table('system_logs')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_youtube_channel_id'))

    op.drop_table('channels')
    # ### end Alembic commands ###
